create table "public"."first_Table" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


CREATE UNIQUE INDEX "first_Table_pkey" ON public."first_Table" USING btree (id);

alter table "public"."first_Table" add constraint "first_Table_pkey" PRIMARY KEY using index "first_Table_pkey";

grant delete on table "public"."first_Table" to "anon";

grant insert on table "public"."first_Table" to "anon";

grant references on table "public"."first_Table" to "anon";

grant select on table "public"."first_Table" to "anon";

grant trigger on table "public"."first_Table" to "anon";

grant truncate on table "public"."first_Table" to "anon";

grant update on table "public"."first_Table" to "anon";

grant delete on table "public"."first_Table" to "authenticated";

grant insert on table "public"."first_Table" to "authenticated";

grant references on table "public"."first_Table" to "authenticated";

grant select on table "public"."first_Table" to "authenticated";

grant trigger on table "public"."first_Table" to "authenticated";

grant truncate on table "public"."first_Table" to "authenticated";

grant update on table "public"."first_Table" to "authenticated";

grant delete on table "public"."first_Table" to "service_role";

grant insert on table "public"."first_Table" to "service_role";

grant references on table "public"."first_Table" to "service_role";

grant select on table "public"."first_Table" to "service_role";

grant trigger on table "public"."first_Table" to "service_role";

grant truncate on table "public"."first_Table" to "service_role";

grant update on table "public"."first_Table" to "service_role";


