create table "public"."second" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."second" enable row level security;

CREATE UNIQUE INDEX second_pkey ON public.second USING btree (id);

alter table "public"."second" add constraint "second_pkey" PRIMARY KEY using index "second_pkey";

grant delete on table "public"."second" to "anon";

grant insert on table "public"."second" to "anon";

grant references on table "public"."second" to "anon";

grant select on table "public"."second" to "anon";

grant trigger on table "public"."second" to "anon";

grant truncate on table "public"."second" to "anon";

grant update on table "public"."second" to "anon";

grant delete on table "public"."second" to "authenticated";

grant insert on table "public"."second" to "authenticated";

grant references on table "public"."second" to "authenticated";

grant select on table "public"."second" to "authenticated";

grant trigger on table "public"."second" to "authenticated";

grant truncate on table "public"."second" to "authenticated";

grant update on table "public"."second" to "authenticated";

grant delete on table "public"."second" to "service_role";

grant insert on table "public"."second" to "service_role";

grant references on table "public"."second" to "service_role";

grant select on table "public"."second" to "service_role";

grant trigger on table "public"."second" to "service_role";

grant truncate on table "public"."second" to "service_role";

grant update on table "public"."second" to "service_role";


